version: 2.1

orbs:
  jira: circleci/jira@1.3.1

workflows:
  build_and_test:
    jobs:
      - build_test:
          post-steps:
            - jira/notify:
                environment_type: development
                job_type: deployment
                service_id: 'b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlL2I2MmE3MDI0LTZhODktNDg3NC05NmRmLTkyNGZlMDQxOTNiNS9lOTNhMGE5ZS1kNTU2LTExZWMtOGRlYy0wYWJlM2Y0YTY2MDE='

      - external_approval:
          requires:
            - "build_test"
          post-steps:
            - jira/notify:
                environment_type: development
                job_type: deployment
                service_id: 'b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlL2I2MmE3MDI0LTZhODktNDg3NC05NmRmLTkyNGZlMDQxOTNiNS9lOTNhMGE5ZS1kNTU2LTExZWMtOGRlYy0wYWJlM2Y0YTY2MDE='
      - hold_approval:
          type: approval
          requires:
            - external_approval
          post-steps:
            - jira/notify:
                environment_type: development
                job_type: deployment
                service_id: 'b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlL2I2MmE3MDI0LTZhODktNDg3NC05NmRmLTkyNGZlMDQxOTNiNS9lOTNhMGE5ZS1kNTU2LTExZWMtOGRlYy0wYWJlM2Y0YTY2MDE='
      - deploy:
          context:
            - global
          requires:
            - hold_approval
          post-steps:
            - jira/notify:
                environment_type: development
                job_type: deployment
                service_id: 'b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlL2I2MmE3MDI0LTZhODktNDg3NC05NmRmLTkyNGZlMDQxOTNiNS9lOTNhMGE5ZS1kNTU2LTExZWMtOGRlYy0wYWJlM2Y0YTY2MDE='

jobs:
  build_test:
    docker:
      - image: node
    steps:
      - checkout
      - run: 
          name: 'Install NestJs'
          command: npm i -g @nestjs/cli

      - run: npm install 

      - run: 
          name: 'Build application'
          command: npm run build --omit=dev

      - run:
          name: 'Test application'
          command: npm run test

  external_approval:
    parameters:
      wait_external_approval:
        type: boolean
        default: true
    docker:
      - image: node
    steps:
      - run: 
          name: 'Waiting external approval' 
          command:
            'x=1; 
            while  [ <<parameters.wait_external_approval>> ]; 
            do 
              echo "Welcome $(( x++ )) times"; 
              sleep 10;
              if $x -gt 5;
              then 
                echo "Teste ";
                break;
              fi; 
            done'
      
  deploy:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker

      - run: 
          name: 'Docker hub login'
          command: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD

      - run:
          name: 'Build image'
          command: docker build -t ivanmds/test_ci_cd:1.0.2 .

      - run: 
          name: 'Push image'
          command: docker push ivanmds/test_ci_cd:1.0.2
