version: 2.1
orbs:
  jira: circleci/jira@1.0.5

jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: 
          name: 'Install NestJs'
          command: npm i -g @nestjs/cli

      - run: npm install 

      - run: 
          name: 'Build application'
          command: npm run build --omit=dev

      - run:
          name: 'Test application'
          command: npm run test
  deploy:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker

      - run: 
          name: 'Docker hub login'
          command: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD

      - run:
          name: 'Build image'
          command: docker build -t ivanmds/test_ci_cd:1.0.2 .

      - run: 
          name: 'Push image'
          command: docker push ivanmds/test_ci_cd:1.0.2

workflows:
  build_and_test:
    jobs:
      - build:
          post-steps:
            - jira/notify:
                job_type: deployment
                environment_type: <<parameters.environment-type>>
      - hold_approval:
          type: approval
          requires:
            - build
      - deploy:
          context:
            - global
          requires:
            - hold_approval