version: 2.1

jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: npm i -g @nestjs/cli
      - run: npm install 
      - run: npm run build --omit=dev
      - run: npm run test
  deploy:
    docker:
      - image: docker
    steps:
      - run: docker ps
      #- checkout
      #- run: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD
      #- run: docker build -t ivanmds/test_ci_cd:1.0.2 .
      #- run: docker push ivanmds/test_ci_cd:1.0.2

workflows:
  build_and_test:
    jobs:
      - build
      - deploy:
          context:
            - global
          requires:
            - build