version: 2.1

parameters:
  wait_external_approval:
    type: boolean
    default: true

jobs:
  build_test:
    docker:
      - image: node
    steps:
      - checkout
      - run: 
          name: 'Install NestJs'
          command: npm i -g @nestjs/cli

      - run: npm install 

      - run: 
          name: 'Build application'
          command: npm run build --omit=dev

      - run:
          name: 'Test application'
          command: npm run test

  external_approval:
    docker:
      - image: node
    steps:
      - run: 
          name: 'Waiting external approval'
          command: 
            '
            x=1
            while [ $x -le 5 ];
            do
              echo "Welcome $x times";
              x=$(( $x + 1 ));
            done
            
            '
      

  deploy:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker

      - run: 
          name: 'Docker hub login'
          command: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD

      - run:
          name: 'Build image'
          command: docker build -t ivanmds/test_ci_cd:1.0.2 .

      - run: 
          name: 'Push image'
          command: docker push ivanmds/test_ci_cd:1.0.2


workflows:
  build_and_test:
    jobs:
      - build_test
      - external_approval:
          requires:
            - build_test
      - hold_approval:
          type: approval
          requires:
            - external_approval
      - deploy:
          context:
            - global
          requires:
            - hold_approval