version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: npm i -g @nestjs/cli
      - run: npm install 
      - run: npm run build --prod
      - run: npm run test
  test:
    docker:
      - image: node
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build