version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: node
    steps:
      - run: cd ..
      - run: npm i -g @nestjs/cli
      - run: pwd
      - run: ls
      - run: cat package.json 
      - run: npm run build
  test:
    docker:
      - image: node
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build